# Generated by Django 3.0.7 on 2020-06-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='heading',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
